with star as(

    select 
    DATE(TIME) AS DAILY_WEATHER,
    WEATHER,
    TEMP,
    PRESSURE,
    HUMIDITY,
    CLOUDS,

    from {{ source('demo', 'weather') }}
    
),
AGG AS (

    SELECT
    DAILY_WEATHER,
    WEATHER,
    ROUND(AVG(TEMP),2) AS AVG_TEMPERATURE,
    round(AVG(PRESSURE),2) AS AVG_PRESSURE,
    ROUND(AVG(HUMIDITY),2) AS AVG_HUMIDITY,
    ROUND(AVG(CLOUDS),2) AS AVG_CLOUDS,    

    FROM STAR
    GROUP BY DAILY_WEATHER, WEATHER
    QUALIFY ROW_NUMBER() OVER (PARTITION BY DAILY_WEATHER ORDER BY COUNT(WEATHER) DESC)=1 
)
select 
*
FROM AGG